name: Build Windows

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-2022 # Explicitly use windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build for Windows
        run: npm run build

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: release/
          retention-days: 30
